FROM ubuntu:24.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends qemu-system-arm \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work

CMD ["qemu-system-aarch64", "-M", "raspi3b", "-kernel", "/work/kernel8.img", "-serial", "stdio", "-display", "none"]
